# Expose les endpoints Actuator nécessaires au monitoring
management.endpoints.web.exposure.include=health,info,prometheus

# Endpoint Prometheus
management.endpoint.prometheus.enabled=true

# Health details
management.endpoint.health.show-details=always
