apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: portfolio-app-secrets
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "1d531489-b6c1-4b0c-93fd-4e26b28bb003"
    keyvaultName: "kv-hajarazureproje-dev"
    tenantId: "7e337a63-5c53-4eaa-b9ad-54ecb1cc48f2"
    objects: |
      array:
        - |
          objectName: <nom-du-secret-dans-keyvault>
          objectType: secret
