apiVersion: v1
kind: ServiceAccount
metadata:
  name: portfolio-app-sa
  namespace: dev
  annotations:
    azure.workload.identity/client-id: "${UAMI_CLIENT_ID}"
    azure.workload.identity/tenant-id: "7e337a63-5c53-4eaa-b9ad-54ecb1cc48f2"
  labels:
    azure.workload.identity/use: "true"
