apiVersion: v1
kind: ServiceAccount
metadata:
  name: portfolio-app-sa
  namespace: dev
  annotations:
    azure.workload.identity/client-id: "1d531489-b6c1-4b0c-93fd-4e26b28bb003"
    azure.workload.identity/tenant-id: "7e337a63-5c53-4eaa-b9ad-54ecb1cc48f2"
  labels:
    azure.workload.identity/use: "true"
