apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio-app
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dev

  selector:
    matchLabels:
      app: portfolio-app

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
