apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: portfolio-app
    newName: <ACR_LOGIN_SERVER>/portfolio-app
    # En staging, on épingle un tag précis (pas "latest") pour garder
    # une traçabilité exacte de ce qui est déployé — bonne pratique
    # à mentionner : "latest" en dev seulement, jamais au-delà.
    newTag: 5f72be3f

replicas:
  - name: portfolio-app
    count: 2

labels:
  - pairs:
      environment: staging

